# Generated by Django 3.1.7 on 2021-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fiction_or_non',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
